#REPORTS
### CREATE REPORT
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Corolla",
    "year": 1993,
    "lat": 30,
    "lng": 2,
    "milage": 20000,
    "price":70000
}


### Approve Existing Report

PATCH http://localhost:3000/reports/2
Content-Type: application/json

{
    "isApproved": true
}

### Unapprove Existing Report

PATCH http://localhost:3000/reports/2
Content-Type: application/json

{
    "isApproved": false
}

### Get Estimate
GET http://localhost:3000/reports?make=Toyota&model=Corolla&lng=2&lat=29&milage=20000&year=1991