#REPORTS
### CREATE REPORT
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Supra",
    "year": 1991,
    "lat": 1,
    "lng": 1,
    "milage": 10000,
    "price":20000
}


### Approve Existing Report

PATCH http://localhost:3000/reports/2
Content-Type: application/json

{
    "isApproved": true
}

### Unapprove Existing Report

PATCH http://localhost:3000/reports/2
Content-Type: application/json

{
    "isApproved": false
}

### Get Estimate
GET http://localhost:3000/reports?make=toyota&model=supra&lng=1&lat=1&milage=10000&year=1991