### SIGNUP
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email" : "test2@ax.com",
    "password" : "12345"
}

### SIGNIN
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email" : "test2@ax.com",
    "password" : "12345"
}

### SIGNOUT
POST http://localhost:3000/auth/signout

### FIND ONE USER
GET http://localhost:3000/auth/1


### FIND ALL BY EMAIL
GET http://localhost:3000/auth?email=a2@ax.com

### DELETE A USER BY ID

DELETE http://localhost:3000/auth/1

### UPDATE USER
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email" : "a@axx.com",
    "password" : "12345"
}

//HANDY REFERENCES FOR USING COOKIES
###Set a color
GET http://localhost:3000/auth/colors/green

###Get the color
GET http://localhost:3000/auth/colors/

### Who Am I
GET http://localhost:3000/auth/whoami